from distutils.core import setup

setup(
    name='eatcode_img',
    version='1.0',
    install_requires=[
        'PythonMagick',
    ],
    packages=['lib.python3.5.site-packages.pip', 'lib.python3.5.site-packages.pip.req',
              'lib.python3.5.site-packages.pip.vcs', 'lib.python3.5.site-packages.pip.utils',
              'lib.python3.5.site-packages.pip.compat', 'lib.python3.5.site-packages.pip.models',
              'lib.python3.5.site-packages.pip._vendor', 'lib.python3.5.site-packages.pip._vendor.distlib',
              'lib.python3.5.site-packages.pip._vendor.distlib._backport',
              'lib.python3.5.site-packages.pip._vendor.colorama', 'lib.python3.5.site-packages.pip._vendor.html5lib',
              'lib.python3.5.site-packages.pip._vendor.html5lib._trie',
              'lib.python3.5.site-packages.pip._vendor.html5lib.filters',
              'lib.python3.5.site-packages.pip._vendor.html5lib.treewalkers',
              'lib.python3.5.site-packages.pip._vendor.html5lib.treeadapters',
              'lib.python3.5.site-packages.pip._vendor.html5lib.treebuilders',
              'lib.python3.5.site-packages.pip._vendor.lockfile', 'lib.python3.5.site-packages.pip._vendor.progress',
              'lib.python3.5.site-packages.pip._vendor.requests',
              'lib.python3.5.site-packages.pip._vendor.requests.packages',
              'lib.python3.5.site-packages.pip._vendor.requests.packages.chardet',
              'lib.python3.5.site-packages.pip._vendor.requests.packages.urllib3',
              'lib.python3.5.site-packages.pip._vendor.requests.packages.urllib3.util',
              'lib.python3.5.site-packages.pip._vendor.requests.packages.urllib3.contrib',
              'lib.python3.5.site-packages.pip._vendor.requests.packages.urllib3.packages',
              'lib.python3.5.site-packages.pip._vendor.requests.packages.urllib3.packages.ssl_match_hostname',
              'lib.python3.5.site-packages.pip._vendor.packaging',
              'lib.python3.5.site-packages.pip._vendor.cachecontrol',
              'lib.python3.5.site-packages.pip._vendor.cachecontrol.caches',
              'lib.python3.5.site-packages.pip._vendor.webencodings',
              'lib.python3.5.site-packages.pip._vendor.pkg_resources', 'lib.python3.5.site-packages.pip.commands',
              'lib.python3.5.site-packages.pip.operations', 'lib.python3.5.site-packages.setuptools',
              'lib.python3.5.site-packages.setuptools.extern', 'lib.python3.5.site-packages.setuptools.command',
              'lib.python3.5.site-packages.pkg_resources', 'lib.python3.5.site-packages.pkg_resources.extern',
              'lib.python3.5.site-packages.pkg_resources._vendor',
              'lib.python3.5.site-packages.pkg_resources._vendor.packaging', 'lib64.python3.5.site-packages.pip',
              'lib64.python3.5.site-packages.pip.req', 'lib64.python3.5.site-packages.pip.vcs',
              'lib64.python3.5.site-packages.pip.utils', 'lib64.python3.5.site-packages.pip.compat',
              'lib64.python3.5.site-packages.pip.models', 'lib64.python3.5.site-packages.pip._vendor',
              'lib64.python3.5.site-packages.pip._vendor.distlib',
              'lib64.python3.5.site-packages.pip._vendor.distlib._backport',
              'lib64.python3.5.site-packages.pip._vendor.colorama',
              'lib64.python3.5.site-packages.pip._vendor.html5lib',
              'lib64.python3.5.site-packages.pip._vendor.html5lib._trie',
              'lib64.python3.5.site-packages.pip._vendor.html5lib.filters',
              'lib64.python3.5.site-packages.pip._vendor.html5lib.treewalkers',
              'lib64.python3.5.site-packages.pip._vendor.html5lib.treeadapters',
              'lib64.python3.5.site-packages.pip._vendor.html5lib.treebuilders',
              'lib64.python3.5.site-packages.pip._vendor.lockfile',
              'lib64.python3.5.site-packages.pip._vendor.progress',
              'lib64.python3.5.site-packages.pip._vendor.requests',
              'lib64.python3.5.site-packages.pip._vendor.requests.packages',
              'lib64.python3.5.site-packages.pip._vendor.requests.packages.chardet',
              'lib64.python3.5.site-packages.pip._vendor.requests.packages.urllib3',
              'lib64.python3.5.site-packages.pip._vendor.requests.packages.urllib3.util',
              'lib64.python3.5.site-packages.pip._vendor.requests.packages.urllib3.contrib',
              'lib64.python3.5.site-packages.pip._vendor.requests.packages.urllib3.packages',
              'lib64.python3.5.site-packages.pip._vendor.requests.packages.urllib3.packages.ssl_match_hostname',
              'lib64.python3.5.site-packages.pip._vendor.packaging',
              'lib64.python3.5.site-packages.pip._vendor.cachecontrol',
              'lib64.python3.5.site-packages.pip._vendor.cachecontrol.caches',
              'lib64.python3.5.site-packages.pip._vendor.webencodings',
              'lib64.python3.5.site-packages.pip._vendor.pkg_resources', 'lib64.python3.5.site-packages.pip.commands',
              'lib64.python3.5.site-packages.pip.operations', 'lib64.python3.5.site-packages.setuptools',
              'lib64.python3.5.site-packages.setuptools.extern', 'lib64.python3.5.site-packages.setuptools.command',
              'lib64.python3.5.site-packages.pkg_resources', 'lib64.python3.5.site-packages.pkg_resources.extern',
              'lib64.python3.5.site-packages.pkg_resources._vendor',
              'lib64.python3.5.site-packages.pkg_resources._vendor.packaging', 'eatcode_img'],
    url='http://eatcode.net/python/img',
    license='MIT',
    author='Ayub Malik',
    author_email='ayub.malik@gmail.com',
    description='Some imagemagick image helper functions'
)
